#!/bin/sh

# Set these paths appropriately

BIN="/home/torpid/Desktop/HLIN405/TreeTagger/bin"
CMD="/home/torpid/Desktop/HLIN405/TreeTagger/cmd"
LIB="/home/torpid/Desktop/HLIN405/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
