#!/bin/sh

# Set these paths appropriately

BIN="/home/torpid/Desktop/HLIN405/TreeTagger/bin"
CMD="/home/torpid/Desktop/HLIN405/TreeTagger/cmd"
LIB="/home/torpid/Desktop/HLIN405/TreeTagger/lib"

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/german-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german.par
LEXFILE=${LIB}/german-lexicon.txt
FILTER=${CMD}/filter-german-tags

$TOKENIZER -a $ABBR_LIST $* |
# external lexicon lookup
perl $CMD/lookup.perl $LEXFILE |
# tagging
$TAGGER $OPTIONS $PARFILE  | 
# error correction
$FILTER
