#!/bin/sh

# Set these paths appropriately

BIN="/home/torpid/Desktop/HLIN405/TreeTagger/bin"
CMD="/home/torpid/Desktop/HLIN405/TreeTagger/cmd"
LIB="/home/torpid/Desktop/HLIN405/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
